@baseUrl = http://localhost:3333


POST {{ baseUrl }}/transact
Content-Type: application/json

{
   "amount" : 100,
   "title": "test title",
   "type": "credit"
} 
  

###
GET {{ baseUrl }}/transact
Content-Type: application/json


### 
GET {{ baseUrl }}/transact/b126e7f5-a497-40d2-ac8a-6b1a345d9a9c