@baseUrl = http://localhost:3333


POST {{ baseUrl }}/transact
Content-Type: application/json

{
   "amount" : 100,
   "title": "test title",
   "type": "debit"
} 
  

###
GET {{ baseUrl }}/transact
Content-Type: application/json


### 
GET {{ baseUrl }}/transact/20a5b7a5-4431-434b-9e9a-357a4163abe8


###
GET {{ baseUrl }}/transact/summary
Content-Type: application/json